import Header from '@/components/Header'
import Sidebarlinks from '@/components/sidebar/Sidebarlinks'
import './globals.css'

export const metadata = {
  title: 'admin-dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-blue-100'>
        <div className=''>
          <Header />
          <div className='w-full pl-12'>
            <div className='grid grid-cols-12'>
              <div className=''>
                <Sidebarlinks />
              </div>
              <div className='col-span-11 '>{children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
